name=HyundaiDashV1
version=1.0.0
author=eymenyg
maintainer=eymen11.16+gh@gmail.com
sentence=Controls a Hyundai/Kia cluster via CAN bus.
paragraph=Uses predefined cluster properties and pinouts based on the PCB design.
category=Display
url=https://github.com/eymenyg/sim_dash
architectures=*
depends=mcp_can
includes=HyundaiDashV1.h
